services:
  backend:
    build: ./http
    container_name: tg-parse-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./parser/media:/app/media
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
      - MONGODB_DB=${MONGODB_DB}
      - JWT_SECRET=${JWT_SECRET}
      - YANDEX_API_FOLDER=${YANDEX_API_FOLDER}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - bots_bots
  parser:
    build: ./parser
    container_name: tg-parse-parser
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3002"
    volumes:
      - ./parser:/app
      - /app/node_modules
      - ./parser/media:/app/media
    environment:
      - NODE_ENV=development
      - STRING_SESSION=${STRING_SESSION}
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - MEDIA_PATH=${MEDIA_PATH}
      - MONGO_DB_NAME=${MONGODB_DB}
      - API_BASE_URL=${API_BASE_URL}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - STATS_UPDATE_LIMIT=${STATS_UPDATE_LIMIT}
    depends_on:
      - backend
    networks:
      - bots_bots
  frontend:
    build:
      context: ./src
      target: dev
      dockerfile: dockerfile
    container_name: tg-parse-frontend
    restart: unless-stopped
    volumes:
      - ./src:/app/
      - /app/node_modules
    ports:
      - '127.0.0.1:5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - bots_bots

networks:
  bots_bots:
    external: true