FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

# не копируем весь код, используем volume для dev
# COPY . . 

RUN mkdir -p /app/media && chmod 755 /app/media

CMD ["npm", "run", "dev"]
