services:
  frontend:
    build:
      context: .
      target: prod
      dockerfile: dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://tg.chiorio.com/api/}
    container_name: tg-parse-frontend-prod
    restart: unless-stopped
    ports:
      - '127.0.0.1:8082:80'
    environment:
      - NODE_ENV=production
    networks:
      - bots

networks:
  bots:
    driver: bridge