version: '3.0'

services:
  frontend:
    build:
      context: .
      target: dev
      dockerfile: dockerfile
    container_name: tg-parse-frontend-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '127.0.0.1:5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://tg.chiorio.com/api/
    networks:
      - bots

networks:
  bots:
    driver: bridge