FROM node:21-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

FROM base AS builder
ARG VITE_API_URL=https://tg.chiorio.com/api
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

FROM nginx:1.25.3-bookworm AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80